services:
  golang:
    image: taskly:golang
    build:
      dockerfile: docker/golang/Dockerfile
      context: .
      target: production
    ports:
      - '8080:8080'
    volumes:
      - .:/srv

  postgres:
    image: taskly:postgres
    build:
      dockerfile: docker/postgres/Dockerfile
      context: .
      target: production
    expose:
      - 5432
    ports:
      - '9001:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: taskly
      POSTGRES_PASSWORD: postgres
#    volumes:
#      - ./docker/postgres:/var/lib/postgresql/data