services:
  golang:
    image: taskly:golang
    ports:
      - '9000:8080'
    volumes:
      - .:/srv
    command:
      - go run server.go

  postgres:
    image: taskly:postgres
    expose:
      - 5432
    ports:
      - '9001:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: taskly
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data