// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Board struct {
	ID     string           `json:"id"`
	Issues *IssueConnection `json:"issues"`
	Issue  *Issue           `json:"issue"`
}

type BoardConnection struct {
	Edges []*BoardEdges `json:"edges"`
}

type BoardEdges struct {
	Cursor string `json:"cursor"`
	Node   *Board `json:"node"`
}

type CreateIssueInput struct {
	UserID      string  `json:"userId"`
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
}

type Issue struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
}

type IssueConnection struct {
	Edges []*IssueEdges `json:"edges"`
}

type IssueEdges struct {
	Cursor string `json:"cursor"`
	Node   *Issue `json:"node"`
}

type Mutation struct {
}

type Query struct {
}

type User struct {
	ID     string           `json:"id"`
	Name   string           `json:"name"`
	Email  string           `json:"email"`
	Boards *BoardConnection `json:"boards"`
	Board  *Board           `json:"board"`
}
